name: main

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        ghc: ['8.10']

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: actions/cache@v2
        with:
          path: |
            $HOME/.cabal/packages
            $HOME/.cabal/store
          key: cabal-${{ runner.os }}-${{ matrix.ghc }}
      - run: make test

  compiler:
    strategy:
      matrix:
        ghc: ['8.10']
        test: [doctest, spec]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: actions/cache@v2
        with:
          path: |
            $HOME/.cabal/packages
            $HOME/.cabal/store
          key: cabal-${{ runner.os }}-${{ matrix.ghc }}
      - run: '"package kmkm`n  tests: true`n  ghc-options: -Werror -fno-ignore-asserts`n  test-show-details: direct`n" | Out-File cabal.project.local'
        shell: pwsh
        working-directory: compiler
      - run: make build-deps
        working-directory: compiler
      - run: make build
        working-directory: compiler
      - run: make ${{ matrix.test }}
        working-directory: compiler

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: rwe/actions-hlint-setup@v1
      - run: make lint
        working-directory: compiler
